name: ci

on:
  push:
    branches:
      - 'master'
  schedule:
  - cron: '0 7 * * *'

env:
  TZ: Asia/Shanghai
  DOCKERHUB_REPO: wangrui027/lsky-pro

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download and Unzip Upstream Source Code from https://github.com/lsky-org/lsky-pro
        run: |
          curl -OL https://github.com/lsky-org/lsky-pro/archive/refs/heads/master.zip
          unzip *.zip
          mv ./lsky-pro-master/* ./
          mv ./lsky-pro-master/.env.example ./
          rm -rf master.zip lsky-pro-master

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
        
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Install Dependencies
        run: composer install
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
#            linux/386
            linux/amd64
#            linux/arm/v5
#            linux/arm/v7
            linux/arm64
#            linux/mips64le
#            linux/ppc64le
#            linux/s390x
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
